---
title: "DIG Endline analysis"
author: "Calum & Elijah"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
    number_sections: true
    toc: true
    toc_float:
      collapsed: false
---

```{r, echo = FALSE}
# Set the knit preferences
 knitr::opts_chunk$set(echo = TRUE, message = FALSE,
    warning = FALSE, fig.height = 8, fig.width = 14, cache = FALSE)
    options(knitr.kable.NA = "")
    options(kableExtra_view_html = F)
```

```{r, echo = FALSE}
# Load libraries
 library(haven)       # data loading
 library(data.table)  # data manipulation
 library(lme4)        # multi-level models
 library(kableExtra)  # format the tables

# Load data
 d <- haven::read_dta("Data/DIG Household Panel Wide Clean.dta") |> setDT()

# List the relevant variables
 outcomes <- c("percapitaexpenditure", # Names of the outcomes
               "hh_expenditure",
               "percapitaincome")
 names(outcomes) <- c("Per capita expenditure",
                      "HH expenditure",
                      "Per capita income")
 covars   <- c("index_s23",  # Index PWD gender
               "index_s24",  # Index PWD's age
               "index_s211", # Index PWD's marital status
               "index_s212", # Index PWD's is able to read and write
               "index_s213" # Index PWD's highest level of education
    )
 names(covars) <- c(
    "Index PWD is male",
    "Index PWD's age",
    "Index PWD's marital status",
    "Index PWD's is able to read and write",
    "Index PWD's highest level of education"
 )

# Recode women to 0
 d$index_s23[d$index_s23 == 2] <- 0

# Keep only relevant variables
 d <- d[, c(outcomes, covars, "resp_lino", "hhid", "follow",
            "treat", "village", "branch", "district", "endline",
            "pwd_hh"),
            with = F]

# Keep only persons with disabilties at baseline
 d <- d[endline == 1 & pwd_hh == 1, ]

# Reshape wide
 d <- dcast(d, resp_lino + hhid ~ follow, value.var = names(d))

# Remove 999
 d[d == 999] <- NA
```

```{r}
# Functions
# =========

# Function to return summary statistics
summary_cells <- function(v) {
    # if binary, return n/N and %
    # if continuous, return the mean and SD
    if (length(unique(v)) < 4) {
        p <- paste0(sum(v == 1, na.rm = T), "/",
               sum(!is.na(v)), " (",
               round(100 * mean(v, na.rm = T), 0), "%)")
    } else {
        p <- paste0(format(mean(v, na.rm = T), big.mark = ",", digits = 0, scientific = F), " (",  #nolint
               format(sd(v, na.rm = T), big.mark = ",", digits = 0, scientific = F), ")") #nolint   
    }
  if (sum(is.na(v)) > 0) {
    p <- paste0(p, " [", sum(is.na(v)), "]")
  }
  return(p)
}

# Function to estimate the difference between the arms
effect_estimates <- function(Y,
                             cvars = c("branch_1", "district_1"),
                             log_y = FALSE) {
    if (log_y == TRUE) Y <- log(Y)
    # Fit the model
    form <- paste0(Y, " ~ treat_1 + (1 | village_1) + ",  ## cluster == cID 
                      paste(cvars, collapse = " + ")) |> as.formula()
    m <- lmer(form, data = d)
    s <- summary(m)
    e <- c(s$coefficients["treat_1", 1], confint(m)["treat_1", ])
    paste0(format(e[1], big.mark = ",", digits = 0, scientific = F), " (",
           format(e[2], big.mark = ",", digits = 0, scientific = F), " to ",
           format(e[3], big.mark = ",", digits = 0, scientific = F), ")")
}
``` 

* Note that the treatment variable has been **scrambled** so these are _not_ the trial results

# TABLES
## TABLE 1: balance checks 

```{r}
vars <- lapply(c(outcomes, covars), function(X) paste0(X, "_0")) |> unlist()

table1 <- d[!is.na(treat_0),
            lapply(.SD, summary_cells),
            by = treat_0,
            .SDcols = vars] |>
            t()

rownames(table1) <- c("", names(vars))

table1[2:nrow(table1), ] |>
    knitr::kable(col.names = c(paste0("Control (N=",
                                      sum(d$pwd_hh_0[d$treat_0 == 0], na.rm = T), ")"), #nolint
                               paste0("DIG Arm (N=",
                                      sum(d$pwd_hh_0[d$treat_0 == 1], na.rm = T), ")") #nolint
                              )) |>
    kableExtra::kable_paper()
```

* Need to recode the categorical variables as dummies for each level
* What other baseline characteristics should we include?

## Figure 2: histogram of the primary outcome

```{r}
par(mfrow = c(1, 2))
hist(d$percapitaincome_1[d$treat_0 == 0])
hist(d$percapitaincome_1[d$treat_0 == 1])

par(mfrow = c(1, 2))
hist(log(d$percapitaincome_1[d$treat_0 == 0]))
hist(log(d$percapitaincome_1[d$treat_0 == 1]))
```

## TABLE 2: effect of the intervention 

```{r}  
# Set names of the outcomes at endline
 outcomes_1  <- lapply(outcomes, function(X) paste0(X, "_1"))
            
# Run the regressions
 effects <- lapply(outcomes_1, effect_estimates) |> unlist()
 adjusted_effects <- lapply(outcomes_1,
                                function(Y) {
                                    effect_estimates(Y,
                                        cvars = c("branch_1", "district_1", # design vars #nolint
                                                  "index_s24_0",  # other baseline covariates #nolint
                                                  paste0(gsub(".{2}$", "", Y), "_0")) # baseline level of the outcome #nolint
                                            )
                                        }
                                      ) |> unlist()

# Combine into a table
 table2 <- d[!is.na(treat_1),
    lapply(.SD, summary_cells),
    by      = treat_1,
    .SDcols = unlist(outcomes_1)] |>
    t() |>
    cbind(c("", effects), c("", adjusted_effects))
 rownames(table2) <- c("", names(outcomes))
 table2[2:nrow(table2), ] |>
    knitr::kable(col.names = c("Control", "DIG Arm", "Unadjusted effect", "Adjusted effect")) |>
    kableExtra::kable_paper()
```
